services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - frontend
      - backend
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/next/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/var/www/html
      - /var/www/html/frontend/node_modules/ # 初回インストール時にDockerfileで生成したものを上書きされないようにする 
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/laravel/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        ENV_EXTENSION: ${ENV_EXTENSION:-dev}
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  # cdk:
  #   build:
  #     context: ./cdk
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../infra:.
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - backend
  #     - frontend

volumes:
  db-data:
